---
# deploy rhamt web console on OpenShift

- debug:
    msg:
      - Openshift project
      - -> Check if {{ OCP_PROJECT }} project exists
- name: check if {{ OCP_PROJECT }} project exists
  shell: "oc get project {{ OCP_PROJECT }}"
  register: labs_infra_project_result
  ignore_errors: true
  changed_when: false

- debug:
    msg:
      - Openshift project
      - -> Create Openshift project ({{ OCP_PROJECT }})

- name: create {{ OCP_PROJECT }} project
  shell: |
     oc new-project {{ OCP_PROJECT }} > /dev/null
     sleep 1
     oc project {{ OCP_PROJECT }} > /dev/null
     sleep 1
     oc policy add-role-to-user view system:serviceaccount:{{ OCP_PROJECT }}:eap-service-account -n {{ OCP_PROJECT }}
     oc policy add-role-to-user view system:serviceaccount:{{ OCP_PROJECT }}:sso-service-account -n {{ OCP_PROJECT }}
     sleep 1
  when: labs_infra_project_result is failed

- debug:
    msg:  -> Process RHAMT Web Template

# Template adapted from https://github.com/jboss-container-images/redhat-sso-7-openshift-image/blob/sso72-dev/templates/sso72-postgresql-persistent.json
- name: Process RHAMT Web Template
  shell: |
     oc process -f https://raw.githubusercontent.com/danieloh30/rhamt/master/templates/web-template.json \
          -p SSO_REALM=rhamt \
          -p POSTGRESQL_MAX_CONNECTIONS=200 \
          -p DB_DATABASE={{ DB_DATABASE }} \
          -p DB_USERNAME={{ DB_USERNAME }} \
          -p DB_PASSWORD={{ DB_PASSWORD }} \
          -p VOLUME_CAPACITY={{ RHAMT_VOLUME_CAPACITY }} \
          -p REQUESTED_CPU={{ REQUESTED_CPU }} \
          -p REQUESTED_MEMORY={{ REQUESTED_MEMORY }} \
          -p DOCKER_IMAGES_TAG={{ DOCKER_IMAGES_TAG }} | oc create -n {{ OCP_PROJECT }} -f -
     sleep 1
  ignore_errors: true